[package]
name = "royalties-splitter-system-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.royalties-splitter-system]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.35.0"
