FROM php:7.4.3-apache

RUN docker-php-ext-install mysqli pdo pdo_mysql

RUN apt-get clean
RUN apt-get update
RUN apt-get install -y

RUN a2enmod ssl && a2enmod rewrite
RUN mkdir -p /etc/apache2/ssl

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
RUN sed -i 's/upload_max_filesize = 20M/upload_max_filesize = 128M/g' "$PHP_INI_DIR/php.ini"
RUN sed -i 's/whatever_option = 1234/whatever_option = 4321/g' "$PHP_INI_DIR/php.ini"
RUN echo 'extension=zip.so' >> "$PHP_INI_DIR/php.ini"

COPY ./certs/*.pem /etc/apache2/ssl/
COPY ../000-default.conf /etc/apache2/sites-available/000-default.conf

EXPOSE 80
EXPOSE 443
