data:
    collection: bayard
    description: NFT exclusifs sur les personnages de bayard
    family: nfluent
    files: ''
    properties: 'Perso1=TomTom

        Perso2=SamSam

        Perso3=Zouk

        Perso4=MortelleAdele'
    symbol: bayard__idx__
    title: BayardSerie
filename_format: image
fontstyle:
    color: '#FFFFFF'
    name: AGENCYB.TTF
    size: 32.8
height: 500
layers:
-   elements:
    -   image: http://127.0.0.1:4242/api/images/-0x23bf9b7c9834121c.webp?webp
    -   image: http://127.0.0.1:4242/api/images/-0x7a7a2d4663c44287.webp?webp
    -   image: http://127.0.0.1:4242/api/images/-0xa7f05de01ab0f4e.webp?webp
    -   image: http://127.0.0.1:4242/api/images/0x26a6ce877d37f072.webp?webp
    -   image: http://127.0.0.1:4242/api/images/0x512ee366ccc271a3.webp?webp
    -   image: http://127.0.0.1:4242/api/images/0xf0d369d4c97c92a.webp?webp
    -   image: http://127.0.0.1:4242/api/images/0x7d726c6507bf1392.webp?webp
    indexed: true
    name: layer2
    params: {}
    position: 0
    text: ''
    unique: false
-   elements:
    -   image: http://127.0.0.1:4242/api/images/-0x737096dd37ce2bd.webp?webp
    -   image: http://127.0.0.1:4242/api/images/0x6ddf2a09897594c1.webp?webp
    -   image: http://127.0.0.1:4242/api/images/-0xd40c804e7a42d05.webp?webp
    -   image: http://127.0.0.1:4242/api/images/-0x642916043c1a49f5.webp?webp
    -   image: http://127.0.0.1:4242/api/images/0x1d6c10cc555faf40.webp?webp
    -   image: http://127.0.0.1:4242/api/images/0x3e6f4ba64fdb2386.webp?webp
    indexed: true
    name: layer1
    params: {}
    position: 2
    text: ''
    unique: false
-   elements:
    -   image: http://127.0.0.1:4242/api/images/0x37c2b3d5a5d436eb.webp?webp
    -   image: http://127.0.0.1:4242/api/images/0x79cef66783c8955f.webp?webp
    -   image: http://127.0.0.1:4242/api/images/0x4e0b4dad72de5173.webp?webp
    -   image: http://127.0.0.1:4242/api/images/0x5da9603bfb5d4fe4.webp?webp
    indexed: true
    name: perso
    params: {}
    position: 2
    text: ''
    unique: false
limit: 200
platform: nfluent_local
seed: 0
text_to_add: '50'
width: 500
x: 5
y: 26
