attributes: {}
data:
    description: ''
    files: ''
    operation: ''
    properties: ''
    sequence: []
    symbol: token__idx__
    tags: ''
    title: ''
height: 200
layers:
-   elements: []
    indexed: true
    name: fond
    params: {}
    position: 0
    scale:
        x: 1
        y: 1
    text: ''
    translation:
        x: 0
        y: 0
    unique: false
-   elements: []
    indexed: true
    name: image
    params: {}
    position: 1
    scale:
        x: 1
        y: 1
    text: ''
    translation:
        x: 0
        y: 0
    unique: false
-   elements: []
    indexed: true
    name: texte
    params: {}
    position: 2
    scale:
        x: 1
        y: 1
    text: ''
    translation:
        x: 0
        y: 0
    unique: false
limit: 10
location: maconf.yaml
max_items: 0
name: maconf
platform:
    label: ''
    value: ''
quality: 98
seed: 0
text:
    color: '#FFFFFF'
    font:
        file: corbel.ttf
        name: Corbel
    fontsize: 12
    position_text:
        x: 10
        y: 10
    text_to_add: Texte ici
width: 200
