attributes: []
data:
    collection: macollection
    description: madescription
    files: http://monfichier
    nftlive:
        datestart: ''
        duration: 120
        timestart: ''
    operation: ''
    properties: propriete=valeur
    symbol: token__idx__
    title: MonTitre
filename_format: image
fontstyle:
    color: '#FFFFFF'
    name: AGENCYB.TTF
    size: 12
height: 200
layers: []
limit: 10
nftlive:
    datestart: ''
    duration: 120
    timestart: ''
platform: nfluent
seed: 0
text_to_add: Texte ici
width: 200
x: 10
y: 10
