attributes: {}
data:
    description: "Carte privil\xE9ge NFluenT"
    files: https://nfluent.io
    operation: Main_devnet
    properties: ''
    sequence:
    - Texte ici
    symbol: token__idx__
    tags: ''
    title: NFluenTAccessCard
height: 800
layers:
-   elements:
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(21)_-0x42e46cca571eca9f.webp?webp
        name: plan_de_travail_(21)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(20)_0x7f7e6813562c85ca.webp?webp
        name: plan_de_travail_(20)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(1)_-0x5511f0ad67e8425e.webp?webp
        name: plan_de_travail_(1)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(22)_0x6ef4f5b0b5b122ef.webp?webp
        name: plan_de_travail_(22)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(24)_0x11495b8d3788a15f.webp?webp
        name: plan_de_travail_(24)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(25)_-0x7be1c120d9f5e842.webp?webp
        name: plan_de_travail_(25)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(27)_-0x4be2cf577110242a.webp?webp
        name: plan_de_travail_(27)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(26)_-0x14ad7f871a63725f.webp?webp
        name: plan_de_travail_(26)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(23)_0xbfa72b56168fa8a.webp?webp
        name: plan_de_travail_(23)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(33)_-0x14e8529456c3a390.webp?webp
        name: plan_de_travail_(33)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(32)_0x3f2d2c982ae39c5b.webp?webp
        name: plan_de_travail_(32)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(28)_0x7cc89e427219f107.webp?webp
        name: plan_de_travail_(28)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(35)_0x37cd9caea0417528.webp?webp
        name: plan_de_travail_(35)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(34)_0x7cd5e5bd6cf191a0.webp?webp
        name: plan_de_travail_(34)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(37)_-0x68d4b30e1436f7e2.webp?webp
        name: plan_de_travail_(37)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(36)_-0x262ae349b8f768dc.webp?webp
        name: plan_de_travail_(36)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(30)_0x6193eb586d8b890b.webp?webp
        name: plan_de_travail_(30)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(31)_-0x6e3ee1840be4a803.webp?webp
        name: plan_de_travail_(31)
    -   image: https://server.f80lab.com:4242/api/images/plan_de_travail_(29)_0x4e87fa7771565b2a.webp?webp
        name: plan_de_travail_(29)
    indexed: true
    name: fond
    params: {}
    position: 0
    scale:
        x: 1
        y: 1
    text: ''
    translation:
        x: 0
        y: 0
    unique: false
-   elements:
    -   image: https://server.f80lab.com:4242/api/images/graphisme((3)_-0x248328d204979736.webp?webp
        name: graphisme((3)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((4)_0x16883a5246b1a272.webp?webp
        name: graphisme((4)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((1)_-0x48bf97e2aae27d1b.webp?webp
        name: graphisme((1)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((2)_-0x5c50c8d1c317d53b.webp?webp
        name: graphisme((2)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((7)_0x7cef1d74cbf857bf.webp?webp
        name: graphisme((7)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((6)_0x29be6b1b74e634ef.webp?webp
        name: graphisme((6)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((5)_0x65ad1ea29a1a6f69.webp?webp
        name: graphisme((5)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((11)_0x54f4b1d90fa47910.webp?webp
        name: graphisme((11)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((8)_0x519be4009c139b9.webp?webp
        name: graphisme((8)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((9)_-0x580e6f7a8a20897f.webp?webp
        name: graphisme((9)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((12)_0x741cd6b051e225a0.webp?webp
        name: graphisme((12)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((10)_0x5ae909236ed9da76.webp?webp
        name: graphisme((10)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((13)_0x565cab5d7331b2cd.webp?webp
        name: graphisme((13)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((17)_0xbb2c663b338d209.webp?webp
        name: graphisme((17)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((14)_-0x5d035bc622d6a33b.webp?webp
        name: graphisme((14)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((16)_0x71c37606892cd58e.webp?webp
        name: graphisme((16)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((15)_0x3c7a4aec0e9ca652.webp?webp
        name: graphisme((15)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((18)_0x57d6add87d775140.webp?webp
        name: graphisme((18)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((22)_-0x7736158fb3295a.webp?webp
        name: graphisme((22)
    -   image: https://server.f80lab.com:4242/api/images/graphisme((23)_-0x314d5a381b1a832f.webp?webp
        name: graphisme((23)
    indexed: true
    name: image
    params: {}
    position: 1
    scale:
        x: 1
        y: 1
    text: ''
    translation:
        x: 0
        y: 0
    unique: false
-   elements:
    -   image: http://127.0.0.1:4242/api/images/svg_0x7d0728efe0c9a692.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x2635e6ad01f0a600.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x671664773ddbe81b.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x4f8062e1b8496ed6.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0xc9fc695613ca4c2.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x5b5ba69f6a97e23b.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x9c0926bd3f8774e.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x7e9025249405926f.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x35b790f7a0965271.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x61ef3ac20e8678ca.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x331375d71cbff644.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x2733479c942e45ed.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x78b009958dc70b16.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x6a1e1ace3e5660d0.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x2eae938f7ec4c3b6.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x359a77ed7bafa2fe.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x1c8e12bcd76240e0.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x2c8f42fbb14e2ffc.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0xe80fdcf7d9ad60.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x59ddfd258accec38.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x3f0980a6d4bf0d59.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x54c7d515052204e0.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x278436f75ea2ef5e.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x3ddcbe04c14cd66a.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x202f3c130a6c0b8e.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x3765bfb9cc48602c.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x37289269f3203c25.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x6573886c320b1ea6.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x1dbd513393b58b54.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x5840321b2a141bf0.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x152db58c4c9bc290.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x53cfd2aaefc4c0d.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x532fbc02edd6aa5f.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x8c86fa880fd5eb2.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x597b3ed6ca4f7d41.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x154e153c49e26c2e.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0xa5fdf39cf2f4c16.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x5d31a8a8f8c11e5e.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x67a68ee21d319a2b.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x6428901eb77202f9.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x397e26fd32c51adc.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x791f1e24ff78cffd.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x326f9d81c3c9adc2.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x1fd36ef54191779b.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x569fd016cfb370f3.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0xf8f3ca9a78ab939.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x1cce53719df21c18.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0xc25b1dedadeb4d0.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x678f14f6e2551ba8.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x18f72b3fbe6966e.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x602e2df67fc08d5c.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x35c387809b4f76db.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x24dc0f90553d00ed.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x71a624291ecf0782.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0xe71ec005fabdef2.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x6760a0829a6bb9aa.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x3e152ee8ac782cc5.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x5d7fb2c08e730132.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x243a180296ba539b.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x70146f7e1abd9447.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x64594ad5258e431a.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x655987d017e95225.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x5aa8e4d44220c42.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x1ea6dbac4cc57723.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x6f7c36590079883a.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x43ba77c0d768c2b6.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x341cc3a5b36f3f41.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x42ad41e641424d44.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x629d2fa171b665c3.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x3e834ecab14cb14a.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x1b571759abd9b5df.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x6786a397647d754f.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x7f8038487d2987e8.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x1f7b88f3ddb79ca9.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x209267dde0548f0.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x6175331b8b18ab9c.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x4d87452447f2f707.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x1f46a00738664c3d.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x14164702b163c7.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x406645082b89766d.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x5181261a0ab6bf4a.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x4fe539afd7e711fb.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x5fe01933679a44a3.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x2369a824208516c.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x5a75daa433ef98f0.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x6b83914a433952d5.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x52e181aac4fb72eb.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x78462dc25ea1d3d5.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x388979ad93fe7c2c.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x26e9d1666d6e9886.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x35fbf5bf90d0a0cd.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x318634a17dfd9652.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x7b6ebe1e951a5280.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x901472b188cc63a.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x50bb271b899e6117.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x7ff67f7d56f53ce7.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x6a3c5975e43da3a5.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x151f2de78cd5bba7.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_-0x20f8f5983fdf0617.svg
        name: nfluentaccess card
    -   image: http://127.0.0.1:4242/api/images/svg_0x5020690266d8c08d.svg
        name: nfluentaccess card
    indexed: false
    name: texte
    params: {}
    position: 2
    scale:
        x: 1
        y: 1
    text: ''
    translation:
        x: 0
        y: 0
    unique: true
limit: 100
location: NFluentAccessCard.yaml
max_items: 0
name: NFluentAccessCard
platform:
    label: ''
    value: ''
quality: 98
seed: 1
text:
    color: '#FFFFFF'
    font:
        file: corbel.ttf
        name: Corbel
    fontsize: 12
    position_text:
        x: 10
        y: 10
    text_to_add: Texte ici
width: 800
