data:
    collection: test
    description: NFT exclusif pour les 50 ans
    family: nfluent
    files: ''
    nftlive:
        datestart: ''
        duration: 120
        timestart: ''
    operation: Main_devnet
    properties: ''
    sequence:
    - '001'
    - '002'
    - '003'
    - '004'
    - '005'
    - '006'
    - '007'
    - 008
    - 009
    - '010'
    symbol: anniv02
    title: Test
filename_format: image
fontstyle:
    color: '#FFFFFF'
    name: AGENCYB.TTF
    size: 26.7
height: 500
layers:
-   elements:
    -   image: http://127.0.0.1:4242/api/images/svg_0x975dd1021c8a.svg
    -   image: http://127.0.0.1:4242/api/images/svg_0x975dd1021d52.svg
    -   image: http://127.0.0.1:4242/api/images/svg_0x975dd1021e7f.svg
    -   image: http://127.0.0.1:4242/api/images/svg_0x975dd1021f46.svg
    -   image: http://127.0.0.1:4242/api/images/svg_0x975dd102200e.svg
    -   image: http://127.0.0.1:4242/api/images/svg_0x975dd10220d6.svg
    -   image: http://127.0.0.1:4242/api/images/svg_0x975dd102219e.svg
    -   image: http://127.0.0.1:4242/api/images/svg_0x975dd1022266.svg
    -   image: http://127.0.0.1:4242/api/images/svg_0x975dd102232e.svg
    -   image: http://127.0.0.1:4242/api/images/svg_0x975dd10223f6.svg
    indexed: true
    name: layer2
    params: {}
    position: 2
    text: ''
    unique: false
limit: 10
nftlive:
    datestart: ''
    duration: 120
    timestart: ''
platform: nfluent
seed: 0
text_to_add: 001|002|003|004|005|006|007|008|009|010
width: 500
x: 4.5
y: 78
