attributes: {}
data:
    description: "D\xE9monstration NFT Live pour la philarmonie"
    files: 'https://philharmoniedeparis.fr/fr

        https://nfluent.io'
    operation: ''
    properties: ''
    sequence: []
    symbol: token__idx__
    tags: ''
    title: PhilarmonieNFTLive
height: 200
layers:
-   elements:
    -   image: https://server.f80lab.com:4242/api/images/philharmonie_de_paris_2010_logo_0x14e6366dabc08d92.webp?webp
        name: philharmonie_de_paris_2010_logo
    indexed: true
    name: texte
    params: {}
    position: 2
    scale:
        x: 1
        y: 1
    text: ''
    translation:
        x: 0
        y: 0
    unique: false
limit: 10
location: philharmonie_nftlive.yaml
max_items: 0
name: philharmonie_nftlive
platform:
    label: ''
    value: ''
quality: 98
seed: 0
text:
    color: '#FFFFFF'
    font:
        file: corbel.ttf
        name: Corbel
    fontsize: 12
    position_text:
        x: 10
        y: 10
    text_to_add: Texte ici
width: 200
